#!/bin/bash

syntax="./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
if [ "$1" != "-p" ]
then 
	echo $syntax
elif [ "$3" != "-o" ]
then
	echo $syntax
elif [ "$5" != "-n" ]
then
	echo $syntax
elif [ "$7" != "-u" ]
then
	echo $syntax
elif [ "$9" != "-i" ]
then
	echo $syntax
else

	replica_servers=(ec2-54-174-6-90.compute-1.amazonaws.com ec2-54-149-9-25.us-west-2.compute.amazonaws.com ec2-54-67-86-61.us-west-1.compute.amazonaws.com ec2-54-72-167-104.eu-west-1.compute.amazonaws.com ec2-54-93-182-67.eu-central-1.compute.amazonaws.com ec2-54-169-146-226.ap-southeast-1.compute.amazonaws.com ec2-54-65-104-220.ap-northeast-1.compute.amazonaws.com ec2-54-66-212-131.ap-southeast-2.compute.amazonaws.com ec2-54-94-156-232.sa-east-1.compute.amazonaws.com)

	ssh $9 ${10} $8@cs5700cdnproject.ccs.neu.edu sh dnsserver $1 $2 $5 $6 &


	for replica in ${replica_servers[*]}

	do
	#echo $replica
	ssh $9 ${10} $8@$replica sh httpserver $1 $2 $3 $4 &
	#ssh $8@$replica sh httpserver $1 $2 $3 $4 &

	done

fi